### ISSUE TITLE
Merge QNMSchwarzschild and QNMKerr

### ISSUE THREAD

**Issue by barrywardell** [BlackHolePerturbationToolkit/QuasiNormalModes#3]
I suggest merging the two functions for calculating QNMs for Kerr and Schwarzschild into a single function, with the Schwarzschild version being recovered when `a=0`.

In sticking with `Mathematica` conventions (as in issue #2), I suggest naming the common function `QuasinormalMode`.

**Comment by ghost** [comment]
This has been done. The two have been merged into QuasiNormalMode, which recovers the relevant function depending on the value of a.
