### ISSUE TITLE
Contribute code to Black Hole Perturbation Toolkit

### ISSUE THREAD

**Issue by barrywardell** [BlackHolePerturbationToolkit/QuasiNormalModes#4]
This code would be an ideal addition to the [Black Hole Perturbation Toolkit](http://blackholeperturbationtoolkit.github.io/). I suggest contributing it to the toolkit and moving the repository there.

**Comment by ghost** [comment]
I can't transfer the repository yet, as I don't have permission to create a repository in the Toolkit.

**Comment by ghost** [comment]
Done.
